### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function query()

### ISSUE THREAD

**Issue by elnarvi** [litespeedtech/lscache_prestashop#44] opened 2021-05-31 11:26 UTC
It is very unstable, it generates 500 random errors, problem detected in Prestashop 1.6.x and 1.7.x

`
2021-05-31 02:00:46.426075 [NOTICE] [11712] [186.83.234.62:47870:HTTP2-65#APVH_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com:443] [STDERR] PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/DbPDO.php:165
Stack trace:
#0 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/Db.php(376): DbPDOCore->_query('\n\t\t\tSELECT `iso...')
#1 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/Db.php(663): DbCore->query('\n\t\t\tSELECT `iso...')
#2 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/Db.php(697): DbCore->getRow('\n\t\t\tSELECT `iso...', true)
#3 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/Country.php(274): DbCore->getValue('\n\t\t\tSELECT `iso...')
#4 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/modules/litespeedcache/classes/VaryCookie.php(234): CountryCore::getIsoById(6)
#5 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/modules/litespeedcache/classes/VaryCookie.php(76): LiteSpee in /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/DbPDO.php on line
165
2021-05-31 02:04:15.721202 [NOTICE] [11712] [66.249.66.77:38770-2#APVH_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com:443] [STDERR] PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/DbPDO.php:165
Stack trace:
#0 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/Db.php(376): DbPDOCore->_query('\n\t\t\tSELECT `iso...')
#1 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/Db.php(663): DbCore->query('\n\t\t\tSELECT `iso...')
#2 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/Db.php(697): DbCore->getRow('\n\t\t\tSELECT `iso...', true)
#3 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/Country.php(274): DbCore->getValue('\n\t\t\tSELECT `iso...')
#4 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/modules/litespeedcache/classes/VaryCookie.php(234): CountryCore::getIsoById(6)
#5 /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/modules/litespeedcache/classes/VaryCookie.php(76): LiteSpee in /var/www/vhosts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/httpdocs/classes/db/DbPDO.php on line
165

`

**Comment by tonimarmol** [comment] 2022-02-25 02:40
@elnarvi did you fix this issue?

**Comment by Eseperio** [comment] 2022-02-25 13:16
Issue is a huge problem. Losing lot of sales

**Comment by tonimarmol** [comment] 2022-02-25 16:01
I migrated from Nginx to OpenLiteSpeed and I had to roll back.

Could it be some incompatibility with PHP 7.1? I am still using Prestashop 1.6 and I am forced to use PHP 7.1.

I want to try updating Prestashop manually with a code seen on your Github https://github.com/PrestaShop/PrestaShop-1.6/issues/3 so it can work with PHP 7.2 and test OLS again with the cache plugin.

**Comment by Eseperio** [comment] 2022-02-25 18:01
It looks like a race condition caused by how LSPHP handles code. The `__destruct` method of Db connection object is called before other classes who are dependand of this.

**Comment by Eseperio** [comment] 2022-02-28 11:37
In order to improve issue readability, i post the code formatted here:
```
 PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/vhosts/domain.com/httpdocs/classes/db/DbPDO.php:165
Stack trace:
#0 /var/www/vhosts/domain.com/httpdocs/classes/db/Db.php(376): DbPDOCore->_query('\n\t\t\t\tSELECT COU...')
#1 /var/www/vhosts/domain.com/httpdocs/classes/db/Db.php(663): DbCore->query('\n\t\t\t\tSELECT COU...')
#2 /var/www/vhosts/domain.com/httpdocs/classes/db/Db.php(697): DbCore->getRow('\n\t\t\t\tSELECT COU...', true)
#3 /var/www/vhosts/domain.com/httpdocs/classes/Language.php(1123): DbCore->getValue('\n\t\t\t\tSELECT COU...')
#4 /var/www/vhosts/domain.com/httpdocs/classes/Language.php(1334): LanguageCore::countActiveLanguages(0)
#5 /var/www/vhosts/domain.com/httpdocs/modules/litespeedcache/classes/VaryCookie.php(245): LanguageCore::isMultiLanguageActivated()
#6 /var/www/vhosts/domain.com/httpdocs/modules/litespeedcache/classes/VaryCookie.php(76): LiteSpeedCacheVaryCookie->init(Object(Context), Object(Cookie))
 in /var/www/vhosts/domain.com/httpdocs/classes/db/DbPDO.php on line 165
```

**Comment by Eseperio** [comment] 2022-02-28 17:27
**Important**
Previous error and the one in the first message **are not the same**, but they have the same origin. 
They are all related with calls on cookie after db destruction, which is a thing that Prestashop contributors addressed [here](https://github.com/PrestaShop/PrestaShop/issues/23281)

**Temp solution**
In Litespeed for Prestashop module configuration, in `Context Vary bypass`, add the following depending on your error:

|Error includes reference to |Bypass param|
|-----|--------------|
|LanguageCore::countActiveLanguages|`lang`|
|GetIsoById|`ctry`|
|Currency|`curr`|

**Comment by therampagerado** [comment] 2023-01-07 17:27
@Eseperio  can you please elaborate how to apply this workaround?


I started seing 500 on all my FO pages and google brought me here. Is there a fix for this issue already?

php 7.4
cache module 1.7
Thirtybees

**Comment by Varindien** [comment] 2023-01-25 16:11
Hello @therampagerado ,

you need to install litespeed module for prestashop and parameters provided by @Eseperio

**Comment by litespeedtech** [comment] 2023-09-05 20:28
vary by "ctry" is removed, should no longer hit this error.

**Closed by litespeedtech** 2023-09-05 20:28 UTC
